apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: ${CONTAINER_REGISTRY}/inventory_management:${VERSION}
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: inventory-management
