name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Build and push images
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:${{ github.sha }} ./book_catalog
          docker push ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:${{ github.sha }}
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:${{ github.sha }} ./inventory_management
          docker push ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to scripts directory and run deploy.sh
        run: |
          cd scripts
          ./deploy.sh
