name: Deploy microservice with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Make scripts executable
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/build-image.sh
          chmod +x ./scripts/push-image.sh
          chmod +x ./scripts/deploy.sh
          chmod +x ./scripts/terraform-init.sh
          chmod +x ./scripts/terraform-apply.sh

      # Builds the Docker image.
      - name: Build
        run: ./scripts/build-image.sh

      # Publishes the Docker image to the container registry.
      - name: Publish
        run: ./scripts/push-image.sh

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the Terraform version you want to use

      # Initialize Terraform
      - name: Terraform Init
        run: ./scripts/terraform-init.sh

      # Apply Terraform changes
      - name: Terraform Apply
        run: ./scripts/terraform-apply.sh
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} # Pass KUBE_CONFIG if needed for Terraform
