name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Build and push images to ACR
        run: |
          set -x  # Enable command logging
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:${{ github.sha }} ./book_catalog
          docker push ${{ secrets.CONTAINER_REGISTRY }}/book_catalog:${{ github.sha }}
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:${{ github.sha }} ./inventory_management
          docker push ${{ secrets.CONTAINER_REGISTRY }}/inventory_management:${{ github.sha }}
          set +x  # Disable command logging

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> $GITHUB_ENV
          echo "DATABASE_URL set to: $DATABASE_URL"  # Log the value for debugging

      - name: Validate environment variables
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "Error: DATABASE_URL is not set."
            exit 1
          fi

      - name: Deploy to AKS
        run: |
          cd scripts
          chmod +x deploy.sh
          set -x  # Enable command logging
          ./deploy.sh
          set +x  # Disable command logging
